@url_local = http://127.0.0.1:3059/v1/api/
### signup
POST {{url_local}}shop/signup
Content-Type: application/json

{
    "name": "Shop_Dung13",
    "email": "shopdung13@gmail.com",
    "password": "Admin@123"
}